apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  name: gitops-depl
  namespace: jane
spec:
  source:
    repoURL: https://github.com/jgwest/gitops-repository-template
    path: environments/overlays/dev
    targetRevision: k8s-only

#  destination: {}

  type: automated

